spring.application.name=springEcom

#given the pdb name at place of db ame
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=SPRING
spring.datasource.password=S12766558#Shu
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
#What they mean:
#update: tries to add/modify basic schema objects, but does not reliably add unique constraints/indexes to existing tables.
#create: drops and recreates schema. This would apply constraints, but you lose existing data.
#create-drop: same as create, then drops schema when app stops. Only for tests/demos.
#validate: checks mapping vs DB, does not change DB.
#none: does nothing.

spring.jpa.show-sql=true
#spring.jackson.deserialization.fail-on-null-for-primitives=false